# -*- coding: utf-8 -*-
"""face.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BTEtyHqKzFp-aMZYyQbH_N7irDc8tDJv
"""

print("hello")

import tensorflow

import cv2

import keras

import dlib

!pip install face_recognition

import face_recognition

print(dir())

import os

os.listdir("/Colab Notebook/Celebrity")

!pwd

!ls

from google.colab import files
uploaded = files.upload()

!ls

images = os.listdir('/content')

images.remove('.config')

images.remove('sample_data')

print(images)

image_to_be_matched = face_recognition.load_image_file('httpimagesfandangocomrImageRendererredesignstaticimgnoxportraitjpgpcpcpcimagesmasterrepositoryperformerimagespjpg.jpg')

image_to_be_matched_encoded = face_recognition.face_encodings(
    image_to_be_matched)[0]

# iterate over each image
for image in images:
    # load the image
    current_image = face_recognition.load_image_file("/content/" + image)
    # encode the loaded image into a feature vector
    current_image_encoded = face_recognition.face_encodings(current_image)[0]
    # match your image with the image and check if it matches
    result = face_recognition.compare_faces(
        [image_to_be_matched_encoded], current_image_encoded)
    # check if it was a match
    if result[0] == True:
        print ("Matched: " + image)
    else:
        print ("Not matched: " + image)